name: client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  device_preview: ^0.4.4
  equatable: ^1.1.1
  flutter_modular: ^1.1.2
  stacked: 1.3.4
  responsive_builder: ^0.1.5
  form_field_validator: ^1.0.1
  flushbar: ^1.10.4
  responsive_framework: ^0.0.7
  intl:
  flutter_icons: ^1.1.0
  country_code_picker: ^1.4.0
  flutter_verification_code: ^0.2.0
  table_calendar: ^2.2.3
  flutter_slidable: ^0.5.4
  charts_flutter: ^0.9.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - Salon.png
    - Shef.png
    - Yoga.png
    - Plumber.png
    - placeholder_photo.jpg
    - Driver.png
    - Dentist.png
    - Cleaner.png
    - Baby_Sitter.png
    - visited_yoga.jpg
    - booking_confirmed.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

